
        <h1 align="center"><strong>Pagina de Status</strong></h1>
        <h3 align="center">Modulos</h3>
    
        <fieldset>
            <div class="col-sm-5">
                <p>
                    <a class="btn btn-danger" href="<?php echo $this->baseUrl('perfil/perfil') ?>">Perfil</a>
                </p>

                <p>
                    <a class="btn btn-primary" href="<?php echo $this->baseUrl('login/login') ?>">Login</a>
                </p>

                <p>
                    <a class="btn btn-danger" href="<?php echo $this->baseUrl('funcionario/funcionario') ?>">Atendente</a>
                </p>
            </div>
                <div class="col-sm-4">

                    <p>
                        <a class="btn btn-default" href="<?php echo $this->baseUrl('') ?>">Relatorios</a>
                    </p>

                    <p>
                        <a class="btn btn-default" href="<?php echo $this->baseUrl('') ?>">Calendario</a>
                    </p>

                    <p>
                        <a class="btn btn-danger" href="<?php echo $this->baseUrl('contato/contato') ?>">Contato</a>
                    </p>
                </div>

        <div class="col-sm-1">
            <div style="width: 90px; height: 30px; border: 20px solid blue;"></div>
            <div style="width: 90px; height: 30px; border: 20px solid red;"></div>
            <div style="width: 90px; height: 30px; border: 20px solid lightseagreen;"></div>
            <div style="width: 90px; height: 30px; border: 20px solid orange;"></div>
            <div style="width: 90px; height: 30px; border: 20px solid whitesmoke;"></div>
        </div>
        <div class="col-sm-1">
            <div style="height: 40px"><span><strong>Aprovado</strong></span></div>
            <div style="height: 40px"><span><strong>Reprovado</strong></span></div>
            <div style="height: 40px"><span><strong>Desenvolvendo</strong></span></div>
            <div style="height: 40px"><span><strong>Em testes</strong></span></div>
            <div style="height: 40px"><span><strong>Outro</strong></span></div>
        </div>
			<a href="https://docs.google.com/document/d/1iZF88sWFLv6sfB-0hJklle3-aslABZ_tf6T24UcPsEA/edit?usp=sharing"
			   target="_blank" class="btn btn-warning">Pendências</a>
    </fieldset>