<form action="<?php echo $this->baseUrl('perfil/gravar'); ?>">
    <input type="hidden"  name="id_perfil" value="<?php echo $this->row['id_perfil']?>">
    <div class="modal-body" >
            <div class="form-group"><label>Nome:</label>
                <input type="text" placeholder="Digite o nome..." class="form-control" name="tx_nome" value="<?php echo $this->row['tx_nome']?>">
            </div>
            <div class="form-group"><label>Descrição</label>
                <input type="text" placeholder="Digite uma breve descrição..." class="form-control" name="tx_descricao" value="<?php echo $this->row['tx_descricao']?>">
            </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-white" data-dismiss="modal">Fechar</button>
        <button type="submit" class="btn btn-primary">Salvar</button>
    </div>
</form>
