    <?php
    /**
     * Created by PhpStorm.
     * User: Diego Denizard
     * Date: 04/09/2016
     */
    ?>
    <link href="<?php echo $this->baseUrl('temas/Inspinia/css/plugins/footable/footable.core.css'); ?>" rel="stylesheet">
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/footable/footable.all.min.js'); ?>"></script>


    <div class="row wrapper border-bottom white-bg page-heading">
                    <div class="col-lg-10" >
                        <h2>Perfil</h2>
                    </div>
                    <div class="col-lg-10">

                    </div>
    </div>
            <div class="wrapper wrapper-content animated fadeInRight">

                <div class="row">
                    <div class="col-lg-18">
                        <div class="ibox">
                            <div class="ibox-title" align="center">
                                <h4>Perfis</h4>
                            </div>
                            <div class="ibox-content">
                                <div class="col-sm-3">
                                <input type="text" class="form-control" id="filter"
                                       placeholder="Procure um Perfil...">
                                </div>

                                <table class="footable table table-stripped" data-page-size="8" data-filter=#filter>
                                    <thead>
                                    <tr>
                                        <th>Ações</th>
                                        <th>Nome</th>
                                        <th>Descrição</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach($this->rowSet as $row){ ?>
                                        <tr>
                                            <td align="left">
                                                <a id="botaoExcluir" class="btn btn-danger btn-circle btn-outline excluirperfil"  data-id-perfil="<?php echo $row['id_perfil'] ?>"><i class="fa fa-trash-o"></i></a>
                                                <a class="btn btn-success btn-circle btn-outline modal-perfil" data-id-perfil="<?php echo $row['id_perfil'] ?>" data-toggle="modal" data-target="#modalNovoPerfil"><i class="fa fa-pencil"></i></a>
                                            </td>
                                            <td align="left"><?php echo $row['tx_nome'] ?></td>
                                            <td align="left"><?php echo $row['tx_descricao'] ?></td>

                                        </tr> <?php } ?>

                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <td colspan="5">
                                            <ul class="pagination pull-right"></ul>
                                        </td>
                                    </tr>
                                    </tfoot>
                                </table>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

    <script>
        $(function () {
            $('.modal-perfil').click(function () {
                
                var id = $(this).data('id-perfil');
                
                $('#modalbody').load('<?php echo $this->baseUrl('perfil/form/id_perfil/') ?>' + id);
            });

        });
       $(document).ready(function () {

           $('.excluirperfil').click(function () {
               var id = $(this).data('id-perfil');

               swal({
                       url: '232',
                       type: "POST",
                       data: {variavel: id},
                       title: "Deletar !!",
                       text: "Você tem certeza que deseja excluir esse perfil ?",
                       type: "warning",
                       showCancelButton: true,
                       confirmButtonColor: "#DD6B55",
                       confirmButtonText: "Sim, quero deletar!",
                       cancelButtonText: "Não",
                       closeOnConfirm: false,
                       closeOnCancel: false },
                   function (isConfirm) {
                       if (isConfirm) {

                           swal("Excluido!", "O perfil foi excluido com sucesso.", "success"),

                            window.location.assign("<?php echo $this->baseUrl('perfil/excluir/id_perfil/') ?>" + id);

                       } else {
                           swal("Cancelado", "O perfil não foi excluido", "error");
                       }
                   });
           });


       });

        $(document).ready(function() {

            $('.footable').footable();
            $('.footable2').footable();

        });

    </script>