    <?php
    /**
     * Created by PhpStorm.
     * User: Diego Denizard
     * Date: 04/09/2016
     */
    ?>
    <div class="row wrapper border-bottom white-bg page-heading">
                    <div class="col-lg-10" >
                        <h2>Perfil</h2>
                    </div>
                    <div class="col-lg-10">

                    </div>
    </div>
            <div class="wrapper wrapper-content  animated fadeInRight">

                <div class="row">
                    <div class="col-lg-18">
                        <div class="ibox">
                            <div class="ibox-title" align="center">
                                <h4>Perfis</h4>
                            </div>
                            <div class="ibox-content">
                                <div class="text-right">
                                    <button type="button"  data-original-title="Criar novo perfil" data-id-perfil="" id="novoperfil" class="btn btn-primary dim btn-outline modal-perfil" data-toggle="modal" data-target="#modalNovoPerfil">
                                        <i class="fa fa-plus-square"></i>
                                        Novo Perfil
                                    </button>
                                    <div class="row">
                                    <div class="col-sm-3">
                                        <div class="input-group"><input type="text" placeholder="Procurar..." class="input-sm form-control"> <span class="input-group-btn">
                                            <button type="button" class="btn btn btn-primary"><i class="fa fa-search"></i></button> </span></div>
                                    </div>
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-striped">
                                        <thead>
                                        <tr>
                                            <th>Nome</th>
                                            <th>Descrição</th>
                                            <th>Ações</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                             <?php foreach($this->rowSet as $row){ ?>
                                        <tr>
                                            <td align="left"><?php echo $row['tx_nome'] ?></td>
                                            <td align="left"><?php echo $row['tx_descricao'] ?></td>
                                            <td align="left">
                                                <a class="btn btn-info btn-circle btn-outline" href="#"><i class="fa fa-cogs"></i></a>
                                                <a class="btn btn-info btn-circle btn-outline" href="<?php echo $this->baseUrl('perfil/excluir/id_perfil/' . $row['id_perfil']); ?>"><i class="fa fa-trash-o"></i></a>
                                                <a class="btn btn-info btn-circle btn-outline modal-perfil" data-id-perfil="<?php echo $row['id_perfil'] ?>" data-toggle="modal" data-target="#modalNovoPerfil"><i class="fa fa-paint-brush"></i></a>
                                            </td>
                                        </tr>
                                             <?php } ?>
                                        
                                        </tbody>
                                    </table>
                                </div>
                                    </div>
                                <div class="modal inmodal" id="modalNovoPerfil" tabindex="-1" role="dialog" aria-hidden="true">
                                    <div class="modal-dialog">
                                    <div class="modal-content animated bounceInRight">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                                                <i class="fa fa-rebel modal-icon"></i>
                                                <h4 class="modal-title">Adicionar Perfil</h4>
                                                <small class="font-bold">Adicione um novo perfil, com nome e desrição.</small>
                                            </div>
                                            <div id="modalbody">

                                            </div>

                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

    <script>
      
       //id = componente.getAttribute("data-id-perfil");
        //id = 1;
        
        $(function () {
            $('.modal-perfil').click(function () {
                
                var id = $(this).data('id-perfil');
                
                $('#modalbody').load('<?php echo $this->baseUrl('perfil/form/id_perfil/') ?>' + id);
            });

        })

    </script>