    <?php
    /**
     * Created by PhpStorm.
     * User: Diego Denizard
     * Date: 04/09/2016
     */
    ?>
    <div class="row wrapper border-bottom white-bg page-heading">
                    <div class="col-lg-10" >
                        <h2>Perfil</h2>
                    </div>
                    <div class="col-lg-10">

                    </div>
    </div>
            <div class="wrapper wrapper-content  animated fadeInRight">

                <div class="row">
                    <div class="col-lg-18">
                        <div class="ibox">
                            <div class="ibox-title" align="center">
                                <h4>Perfis</h4>
                            </div>
                            <div class="ibox-content">
                                <div class="text-right">
                                    <button type="button" data-original-title="Criar novo perfil" class="btn btn-primary dim btn-outline" data-toggle="modal" data-target="#modalNovoPerfil">
                                        <i class="fa fa-plus-square"></i>
                                        Novo Perfil
                                    </button>
                                    <div class="row">
                                    <div class="col-sm-3">
                                        <div class="input-group"><input type="text" placeholder="Procurar..." class="input-sm form-control"> <span class="input-group-btn">
                                            <button type="button" class="btn btn btn-primary"><i class="fa fa-search"></i></button> </span></div>
                                    </div>
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-striped">
                                        <thead>
                                        <tr>
                                            <th>Nome</th>
                                            <th>Descrição</th>
                                            <th>Ações</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td align="left">Fausto Silva</td>
                                            <td align="left">Essa eh a fera Meo</td>
                                            <td align="left">
                                                    <a class="btn btn-info btn-circle btn-outline" href="#"><i class="fa fa-wrench"></i></a>
                                                <a class="btn btn-info btn-circle btn-outline" href="#"><i class="fa fa-times"></i></a>
                                                <a class="btn btn-info btn-circle btn-outline" href="#"><i class="fa fa-paint-brush"></i></a>
                                            </td></tr>
                                        <tr>
                                            <td align="left">Administrador</td>
                                            <td align="left">Delete quem quiser</td>
                                            <td align="left">
                                                <a class="btn btn-info btn-circle btn-outline" href="#"><i class="fa fa-wrench"></i></a>
                                                <a class="btn btn-info btn-circle btn-outline" href="#"><i class="fa fa-times"></i></a>
                                                <a class="btn btn-info btn-circle btn-outline" href="#"><i class="fa fa-paint-brush"></i></a>
                                            </td></tr>
                                        <tr>
                                            <td align="left">Gerente</td>
                                            <td align="left">Ver os relatorios</td>
                                            <td align="left">
                                                <a class="btn btn-info btn-circle btn-outline" href="#"><i class="fa fa-wrench"></i></a>
                                                <a class="btn btn-info btn-circle btn-outline" href="#"><i class="fa fa-times"></i></a>
                                                <a class="btn btn-info btn-circle btn-outline" href="#"><i class="fa fa-paint-brush"></i></a>
                                            </td></tr>
                                        <tr>
                                            <td align="left">Atendente</td>
                                            <td align="left">Atende as Ligações</td>
                                            <td align="left">
                                                <a class="btn btn-info btn-circle btn-outline" href="#"><i class="fa fa-wrench"></i></a>
                                                <a class="btn btn-info btn-circle btn-outline" href="#"><i class="fa fa-times text-navy"></i></a>
                                                <a class="btn btn-info btn-circle btn-outline" href="#"><i class="fa fa-paint-brush  text-navy"></i></a>
                                            </td>
                                        </tr>
                                        
                                        </tbody>
                                    </table>
                                </div>
                                    </div>
                                <div class="modal inmodal" id="modalNovoPerfil" tabindex="-1" role="dialog" aria-hidden="true">
                                    <div class="modal-dialog">
                                    <div class="modal-content animated bounceInRight">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                                                <i class="fa fa-rebel modal-icon"></i>
                                                <h4 class="modal-title">Adicionar Perfil</h4>
                                                <small class="font-bold">Adicione um novo perfil, com nome e desrição.</small>
                                            </div>
                                            <div class="modal-body">
                                                <div class="form-group"><label>Nome:</label> <input type="text" placeholder="Digite o nome..." class="form-control" name="nome"></div>
                                                <div class="form-group"><label>Descrição</label> <input type="text" placeholder="Digite uma breve descrição..." class="form-control" name="descricao"></div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-white" data-dismiss="modal">Fechar</button>
                                                <button type="button" class="btn btn-primary">Salvar</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>