<?php
/**
 * Created by PhpStorm.
 * User: diego
 * Date: 08/09/2016
 */
?>
<link href="<?php echo $this->baseUrl('temas/Inspinia/css/plugins/footable/footable.core.css'); ?>" rel="stylesheet">
<script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/footable/footable.all.min.js'); ?>"></script>

<div class="row wrapper border-bottom bg-success page-heading">
    <div class="col-lg-10" >
        <h2>Histórico</h2>
    </div>
</div>
<div class="wrapper wrapper-content  animated fadeInRight">

    <div class="row">
        <div class="col-lg-16">
            <div class="ibox">
                <div class="ibox-title" align="center">
                    <h4>Histórico</h4>
                </div>
                <div class="ibox-content">
                    <div class="text-right">
                        <button type="button" data-original-title="" onclick="window.location.href='<?php echo $this->baseUrl('historico/novo') ?>';" class="btn btn-primary dim btn-outline">
                            <i class="fa fa-plus-square"></i>
                           Novo Histórico
                        </button>
                        <div class="row">
                            <div class="col-sm-3">
                                <div class="input-group"><input type="text" class="input-sm form-control" id="filter"
                                       placeholder="Procure um histórico..."><span class="input-group-btn">
                                        <button type="button" class="btn btn btn-primary"><i class="fa fa-search"></i></button> </span></div>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="footable table table-stripped" data-page-size="8" data-filter=#filter>
                                <thead>
                                <tr>
                                    <th>Cliente</th>
                                    <th>Data</th>
                                    <th>Ações</th>
                                </tr>
                                </thead>
                                <tbody>


                                <tr>
                                    <td  align="left">SBT</td>
                                    <td  align="left">20/09/2016</td>
                                    <td  align="left">
                                        <a class="btn btn-info btn-circle btn-outline" href="#"><i class="fa fa-paint-brush"></i></a>
                                    </td></tr>
                                <tr>
                                    <td align="left">Exemplo 2</td>
                                    <td align="left">xx/xx/xxxx</td>
                                    <td align="left">
                                        <a class="btn btn-info btn-circle btn-outline" href="#"><i class="fa fa-paint-brush"></i></a>
                                    </td></tr>

                                    <?php foreach($this->rowSetHistorico as $row){ ?>
                                <tr>
                                    <td align="left"><?php echo $row['id_historico'] ?></td>
                                    <td align="left"><?php echo $row['dt_atendimento'] ?></td>
                                    <td align="left">
                                        <a class="btn btn-info btn-circle btn-outline" href="#"><i class="fa fa-paint-brush"></i></a>
                                    </td></tr>
                                       <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="modal inmodal" id="excluir" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content animated bounceInDown">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                                    <i class="fa fa-empire modal-icon"></i>
                                    <h4 class="modal-title">Excluir</h4>
                                </div>
                                <div class="modal-body" align="center">
                                    <div class="form-group"><label><span>Tem certeza que deseja excluir este atendente ?</span></label></div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-white" data-dismiss="modal">Não</button>
                                    <button type="button" class="btn btn-primary">Sim, Excluir</button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {

        $('.footable').footable();
        $('.footable2').footable();

});
</script>
