
        <link href="<?php echo $this->baseUrl('temas/Inspinia/css/plugins/datapicker/datepicker3.css'); ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl('temas/Inspinia/css/plugins/clockpicker/clockpicker.css'); ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl('temas/Inspinia/css/plugins/iCheck/custom.css'); ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl('temas/Inspinia/css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css'); ?>" rel="stylesheet">
        <!-- Clock picker -->
        <script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/clockpicker/clockpicker.js'); ?>"></script>
        <!-- Data picker -->
        <script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/datapicker/bootstrap-datepicker.js'); ?>"></script>
        <!-- iCheck -->
        <script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/iCheck/icheck.min.js'); ?>"></script>
        <!-- Input Mask-->
        <script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/jasny/jasny-bootstrap.min.js'); ?>"></script>

        <form action="<?php echo $this->baseUrl('historico/gravar'); ?>">

            <input type="hidden"  name="id_entidade" value="<?php echo $this->row['id_entidade']?>">
            <input type="hidden"  name="id_endereco" value="<?php echo $this->row['id_endereco']?>">
            <input type="hidden"  name="id_telefone" value="<?php echo $this->row['id_telefone']?>">
            <input type="hidden"  name="id_historico" value="<?php echo $this->row['id_historico']?>">

            <div class="modal-body" >
                    <div class="form-group"><label>Fantasia/Razão Social:</label>
                        <input type="text" placeholder="Fantasia/Razão Social" class="form-control" name="tx_nome" value="<?php echo $this->row['tx_nome']?>">
                    </div>
                    <div class="form-group"><label>Telefone:</label>
                        <input type="text" placeholder="(XX)XXXXX-XXXX" class="form-control" name="tx_nome" value="<?php echo $this->row['tx_nome']?>">
                    </div>
                    <div class="form-group"><label>Nome/Representante:</label>
                        <input type="text" placeholder="Nome/Representante" class="form-control" name="tx_nome" value="<?php echo $this->row['tx_nome']?>">
                    </div>
                    <div class="form-group"><label>Data:</label>
                        <input type="text" placeholder="Data" class="form-control" name="tx_nome" value="<?php echo $this->row['tx_nome']?>">
                    </div>
                    <div class="form-group"><label>Bairro:</label>
                        <input type="text" placeholder="Bairro" class="form-control" name="tx_nome" value="<?php echo $this->row['tx_nome']?>">
                    </div>
                    <div class="form-group"><label>Endereço:</label>
                        <input type="text" placeholder="Endereço" class="form-control" name="tx_nome" value="<?php echo $this->row['tx_nome']?>">
                    </div>
                    <div class="form-group"><label>Número:</label>
                        <input type="text" placeholder="Número" class="form-control" name="tx_nome" value="<?php echo $this->row['tx_nome']?>">
                    </div>
                    <div class="form-group"><label>Assunto/Conversa:</label>
                        <input type="text" placeholder="Assunto/Conversa" class="form-control" name="tx_descricao" value="<?php echo $this->row['tx_descricao']?>">
                    </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Fechar</button>
                <button type="submit" class="btn btn-primary">Salvar</button>
            </div>
        </form>


                <script>
                    $(document).ready(function () {
                        $('.i-checks').iCheck({
                            checkboxClass: 'icheckbox_square-green',
                            radioClass: 'iradio_square-green',
                        });
                    });

                    $('.clockpicker').clockpicker();
                </script>
