<?php
/**
 * Created by PhpStorm.
 * User: Diego Denizard
 * Date: 04/09/2016
 */
?>
<div class="row wrapper border-bottom bg-success page-heading">
    <div class="col-lg-10" >
        <h2>Tela de Funcionários</h2>
    </div>
</div>
<div class="wrapper wrapper-content  animated fadeInRight">

    <div class="row">
        <div class="col-lg-16">
            <div class="ibox">
                <div class="ibox-title" align="center">
                    <h4>Funcionários</h4>
                </div>
                <div class="ibox-content">
                    <div class="text-right">
                        <button type="button" data-original-title="Criar novo perfil" onclick="window.location.href='<?php echo $this->baseUrl('funcionario/add') ?>';" class="btn btn-primary dim btn-outline">
                            <i class="fa fa-plus-square"></i>
                            Novo Funcionario
                        </button>
                        <div class="row">
                            <div class="col-sm-3">
                                <div class="input-group"><input type="text" placeholder="Procurar..." class="input-sm form-control"> <span class="input-group-btn">
                                        <button type="button" class="btn btn btn-primary"><i class="fa fa-search"></i></button> </span></div>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>C.P.F</th>
                                    <th>Ações</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>

                                    <td  align="left">Silvio Santos</td>
                                    <td  align="left">444.444.444-34</td>
                                    <td  align="left">
                                        <a class="btn btn-info btn-circle btn-outline" data-toggle="modal" data-target="#excluir" href="#"><i class="fa fa-times"></i></a>
                                        <a class="btn btn-info btn-circle btn-outline" href="#"><i class="fa fa-paint-brush"></i></a>
                                    </td></tr>
                                <tr>
                                    <td align="left">Exemplo 2</td>
                                    <td align="left">000.000.000.00</td>
                                    <td align="left">
                                        <a class="btn btn-info btn-circle btn-outline" data-toggle="modal" data-target="#excluir" href="#"><i class="fa fa-times"></i></a>
                                        <a class="btn btn-info btn-circle btn-outline" href="#"><i class="fa fa-paint-brush"></i></a>
                                    </td></tr>
                                <tr>
                                    <td align="left">Exemplo 3</td>
                                    <td align="left">111.111.111-11</td>
                                    <td align="left">
                                        <a class="btn btn-info btn-circle btn-outline" data-toggle="modal" data-target="#excluir" href="#"><i class="fa fa-times"></i></a>
                                        <a class="btn btn-info btn-circle btn-outline" href="#"><i class="fa fa-paint-brush"></i></a>
                                    </td></tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="modal inmodal" id="excluir" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content animated bounceInDown">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                                    <i class="fa fa-empire modal-icon"></i>
                                    <h4 class="modal-title">Excluir</h4>
                                </div>
                                <div class="modal-body" align="center">
                                    <div class="form-group"><label><span>Tem certeza que deseja excluir este funcionario ?</span></label></div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-white" data-dismiss="modal">Não</button>
                                    <button type="submit" class="btn btn-primary" action="<?php echo $this->baseUrl('funionario/excluir'); ?>">Sim, Excluir</button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

