<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <h2><strong>Formulario de Novo Cliente</strong></h2>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
<div class="row">
    <div class="col-lg-12">
            <div class="ibox-title">
                <h5>Cadastre um novo cliente</h5>
            </div>
            <div class="ibox-content">

                <label class="col-sm-12">Identificação</label>
                <form method="get" class="form-inline" action="<?php echo $this->baseUrl('cliente/gravar'); ?>">

                    <div class="form-group col-lg-12">
                        <div class="col-sm-12">
                            <div class="input-group m-b">
                                <span class=" form-group input-group-addon fa fa-user"> Nome/Razão Social</span>
                                <input type="text" placeholder="Nome ou Razão Social" class="form-control">
                            </div>
                            <div class="input-group m-b">
                                <span class=" form-group input-group-addon fa fa-credit-card"> C.P.F/C.N.P.J</span>
                                <input type="text" placeholder="CPF ou CNPJ" class="form-control">
                            </div>
                            <div class="input-group m-b">
                                <span class=" form-group input-group-addon fa fa-credit-card"> Inscrição Estadual</span>
                                <input type="text" placeholder="IE" class="form-control">
                            </div>
                            <div class="input-group m-b">
                                <span class=" form-group input-group-addon fa fa-envelope"> E-mail</span>
                                <input type="email" placeholder="@E-mail" class="form-control">
                            </div>
                        </div>
                    </div>

                    <label class="col-sm-12">Endereço</label>
                    <div class="form-group col-lg-12">
                        <div class="col-sm-12">
                            <div class="input-group m-b col-sm-2">
                                <span class=" form-group input-group-addon fa fa-flag"> C.E.P</span>
                                <input type="text" placeholder="CEP" class="form-control">
                            </div>
                            <div class="input-group m-b col-sm-1">
                                <span class=" form-group input-group-addon fa fa-ellipsis-h"> U.F</span>
                                <input type="text" placeholder="UF" class="form-control">
                            </div>
                            <div class="input-group m-b">
                                <span class=" form-group input-group-addon fa fa-ellipsis-h"> Localidade</span>
                                <input type="text" placeholder="Localidade" class="form-control">
                            </div>
                            <div class="input-group m-b">
                                <span class=" form-group input-group-addon fa fa-ellipsis-h"> Bairro</span>
                                <input type="email" placeholder="Bairro" class="form-control">
                            </div>
                            <div class="input-group m-b">
                                <span class=" form-group input-group-addon fa fa-ellipsis-h"> Logradouro</span>
                                <input type="email" placeholder="Logradouro" class="form-control">
                            </div>
                            <div class="input-group m-b col-sm-1">
                                <span class=" form-group input-group-addon fa fa-ellipsis-h"> Número</span>
                                <input type="email" placeholder="Número" class="form-control">
                            </div>
                            <div class="input-group m-b">
                                <span class=" form-group input-group-addon fa fa-ellipsis-h"> Complemento</span>
                                <input type="email" placeholder="Complemento" class="form-control">
                            </div>
                        </div>
                    </div>

                    <label class="col-sm-12">Contato</label>
                    <div class="form-group col-lg-12">
                        <div class="col-sm-12">
                            <div class="input-group m-b">
                                <span class=" form-group input-group-addon fa fa-phone"> Telefone Fixo</span>
                                <input type="text" placeholder="Fixo" class="form-control">
                            </div>
                            <div class="input-group m-b">
                                <span class=" form-group input-group-addon fa fa-mobile-phone"> Telefone Celular</span>
                                <input type="text" placeholder="Celular" class="form-control">
                            </div>
                        </div>
                    </div>
                        <div class="form-group"></div>
                </form>
                    <div class="form-group">
                        <div class="col-sm-12" align="center">
                            <p>
                                <a class="btn btn-white" href="<?php echo $this->baseUrl('cliente/pagina') ?>">Cancelar</a>
                                <button class="btn btn-primary" type="submit">Salvar Cliente</button>
                            </p>
                    </div>
                </div>
            </div>
    </div>
</div>
</div>

<script>
    $(function(){
        $('#cep').change(function () {
            var cep = $('#cep').val();
            $.ajax({
                url:'https://viacep.com.br/ws/'+ cep +'/json/',
                success: function (dados) {
                    $('#uf').val(dados.uf);
                    $('#localidade').val(dados.localidade);
                    $('#bairro').val(dados.bairro);
                    $('#logradouro').val(dados.logradouro);
                    $('#complemento').val(dados.complemento);
                }
            })
        })
    })
</script>