<div class="wrapper wrapper-content  animated fadeInRight">
    <div class="row">
        <div class="">
            <div class="ibox">
                <div class="ibox-content">
                    <h2>Meus Clientes</h2>
                    <p>
                        <strong>Aqui Sera mostrado todos os clientes do funcionario X</strong>
                    </p>
                    <div class="input-group">
                        <input type="text" placeholder="Procurar Cliente ..." class="input form-control">
                        <span class="input-group-btn">
                                        <button type="button" class="btn btn btn-primary"> <i class="fa fa-search"></i> Procurar</button>
                                </span>
                    </div>
                    <div class="clients-list">
                        <ul class="nav nav-tabs">
                            <span class="pull-right small text-muted"> X Quantidade de Clientes</span>
                            <li class="active"><a data-toggle="tab" href="#tab-1"><i class="fa fa-user"></i>Clientes Fisicos</a></li>
                            <li class=""><a data-toggle="tab" href="#tab-2"><i class="fa fa-briefcase"></i>Clientes Juridicos</a></li>
                        </ul>
                        <div class="tab-content">
                            <div id="tab-1" class="tab-pane active">
                                <div class="full-height-scroll">
                                    <div class="table-responsive">
                                        <table class="table table-striped table-hover">
                                            <tbody>
                                            <tr>
                                                <td><a data-toggle="tab" href="" class="client-link">Cliente 1</a></td>
                                                <td>Nome da Empresa ou outro dado</td>
                                                <td class="contact-type"><i class="fa fa-envelope">Tipo Contato</i></td>
                                                <td> contato</td>
                                                <td class="client-status"><span class="label label-primary">Ativo</span> Ativo ou nao</td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="" class="client-link">Silvio Santos</a></td>
                                                <td>SBT</td>
                                                <td class="contact-type"><i class="fa fa-envelope"> </i></td>
                                                <td> silvio@sbt.com</td>
                                                <td class="client-status"><span class="label label-primary">Ativo</span></td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="" class="client-link">Fausto Silva</a></td>
                                                <td>Pizzaria do Faustao</td>
                                                <td class="contact-type"><i class="fa fa-phone"> </i></td>
                                                <td> 61 99999999</td>
                                                <td class="client-status">Inativo</td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="" class="client-link">Ricardo</a></td>
                                                <td>Caldeira Informatica</td>
                                                <td class="contact-type"><i class="fa fa-mail-forward"> </i></td>
                                                <td> ruimnopoker@pokerstars.com</td>
                                                <td class="client-status"><span class="label label-warning">Em Espera</span></td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div id="tab-2" class="tab-pane">
                                <div class="full-height-scroll">
                                    <div class="table-responsive">
                                        <table class="table table-striped table-hover">
                                            <tbody>
                                            <tr>
                                                <td><a data-toggle="tab" href="#company-1" class="client-link">Tellus Institute</a></td>
                                                <td>Rexton</td>
                                                <td><i class="fa fa-flag"></i> Angola</td>
                                                <td class="client-status"><span class="label label-primary">Active</span></td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="#company-2" class="client-link">Velit Industries</a></td>
                                                <td>Maglie</td>
                                                <td><i class="fa fa-flag"></i> Luxembourg</td>
                                                <td class="client-status"><span class="label label-primary">Active</span></td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="#company-3" class="client-link">Art Limited</a></td>
                                                <td>Sooke</td>
                                                <td><i class="fa fa-flag"></i> Philippines</td>
                                                <td class="client-status"></td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="#company-1" class="client-link">Tempor Arcu Corp.</a></td>
                                                <td>Eisden</td>
                                                <td><i class="fa fa-flag"></i> Korea, North</td>
                                                <td class="client-status"><span class="label label-warning">Waiting</span></td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="#company-2" class="client-link">Penatibus Consulting</a></td>
                                                <td>Tribogna</td>
                                                <td><i class="fa fa-flag"></i> Montserrat</td>
                                                <td class="client-status"></td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="#company-3" class="client-link"> Ultrices Incorporated</a></td>
                                                <td>Basingstoke</td>
                                                <td><i class="fa fa-flag"></i> Tunisia</td>
                                                <td class="client-status"><span class="label label-primary">Active</span></td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="#company-2" class="client-link">Et Arcu Inc.</a></td>
                                                <td>Sioux City</td>
                                                <td><i class="fa fa-flag"></i> Burundi</td>
                                                <td class="client-status"><span class="label label-primary">Active</span></td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="#company-1" class="client-link">Tellus Institute</a></td>
                                                <td>Rexton</td>
                                                <td><i class="fa fa-flag"></i> Angola</td>
                                                <td class="client-status"><span class="label label-primary">Active</span></td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="#company-2" class="client-link">Velit Industries</a></td>
                                                <td>Maglie</td>
                                                <td><i class="fa fa-flag"></i> Luxembourg</td>
                                                <td class="client-status"></td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="#company-3" class="client-link">Art Limited</a></td>
                                                <td>Sooke</td>
                                                <td><i class="fa fa-flag"></i> Philippines</td>
                                                <td class="client-status"></td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="#company-1" class="client-link">Tempor Arcu Corp.</a></td>
                                                <td>Eisden</td>
                                                <td><i class="fa fa-flag"></i> Korea, North</td>
                                                <td class="client-status"><span class="label label-warning">Waiting</span></td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="#company-2" class="client-link">Penatibus Consulting</a></td>
                                                <td>Tribogna</td>
                                                <td><i class="fa fa-flag"></i> Montserrat</td>
                                                <td class="client-status"></td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="#company-3" class="client-link"> Ultrices Incorporated</a></td>
                                                <td>Basingstoke</td>
                                                <td><i class="fa fa-flag"></i> Tunisia</td>
                                                <td class="client-status"><span class="label label-primary">Active</span></td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="#company-2" class="client-link">Et Arcu Inc.</a></td>
                                                <td>Sioux City</td>
                                                <td><i class="fa fa-flag"></i> Burundi</td>
                                                <td class="client-status"><span class="label label-primary">Active</span></td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="#company-1" class="client-link">Tellus Institute</a></td>
                                                <td>Rexton</td>
                                                <td><i class="fa fa-flag"></i> Angola</td>
                                                <td class="client-status"><span class="label label-primary">Active</span></td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="#company-2" class="client-link">Velit Industries</a></td>
                                                <td>Maglie</td>
                                                <td><i class="fa fa-flag"></i> Luxembourg</td>
                                                <td class="client-status"></td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="#company-3" class="client-link">Art Limited</a></td>
                                                <td>Sooke</td>
                                                <td><i class="fa fa-flag"></i> Philippines</td>
                                                <td class="client-status"></td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="#company-1" class="client-link">Tempor Arcu Corp.</a></td>
                                                <td>Eisden</td>
                                                <td><i class="fa fa-flag"></i> Korea, North</td>
                                                <td class="client-status"><span class="label label-warning">Waiting</span></td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="#company-2" class="client-link">Penatibus Consulting</a></td>
                                                <td>Tribogna</td>
                                                <td><i class="fa fa-flag"></i> Montserrat</td>
                                                <td class="client-status"></td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="#company-3" class="client-link"> Ultrices Incorporated</a></td>
                                                <td>Basingstoke</td>
                                                <td><i class="fa fa-flag"></i> Tunisia</td>
                                                <td class="client-status"><span class="label label-primary">Active</span></td>
                                            </tr>
                                            <tr>
                                                <td><a data-toggle="tab" href="#company-2" class="client-link">Et Arcu Inc.</a></td>
                                                <td>Sioux City</td>
                                                <td><i class="fa fa-flag"></i> Burundi</td>
                                                <td class="client-status"><span class="label label-primary">Active</span></td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>