<!-- FooTable -->
<link href="<?php echo $this->baseUrl('temas/Inspinia/css/plugins/footable/footable.core.css'); ?>" rel="stylesheet">
<script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/footable/footable.all.min.js'); ?>"></script>


<div class="wrapper wrapper-content  animated fadeInRight">
    <div class="row">
        <div class="">
            <div class="ibox">
                <div class="ibox-content">
                    <h2>Meus Clientes</h2>
                    <p>
                        <strong>Aqui Sera mostrado todos os clientes do funcionario X</strong>
                    </p>
                    <input type="hidden"  data-original-title="Criar novo perfil" data-id-entidade="" id="novocontato" class="btn btn-primary dim btn-outline modal-historico" data-toggle="modal" data-target="#modalNovoHistorico">
                          </input>
                    <div class="col-sm-4 input-group">
                      <p>
                          <a class="btn btn btn-primary right" href="<?php echo $this->baseUrl('cliente/formulario'); ?>"><i class="fa fa-user-plus"></i> Ir para novo Cliente</a>
                      </p>
                    </div>
                    <div class="col-sm-3 input-group">
                    <input type="text" class="input form-control" id="filter"
                           placeholder="Procure Cliente...">
                           <span class="input-group-btn">
                                           <button type="button" class="btn btn btn-primary"> <i class="fa fa-search"></i> Procurar</button>
                                   </span>
                    </div>
                    <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="8" data-filter=#filter>
                        <thead>
                        <tr>

                            <th data-toggle="true">Nome Empresa</th>
                            <th>Nome Cliete/Representante</th>
                            <th>Telefone</th>
                            <th data-hide="all">Endereço</th>
                            <th data-hide="all">Último Contato</th>
                            <th data-hide="all">Próximo Contato</th>
                            <th>Ações</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>Hipermerado Extra</td>
                            <td>Patrick Smith</td>
                            <td>0800 111111</td>
                            <td>Setor Comercial Sul</td>
                            <td>20/05/2016</td>
                            <td>20/06/2016</td>
                            <td><a href="<?php echo $this->baseUrl('agenda/calendario'); ?>"><i class="fa fa-calendar"></i></a>
<a class="btn btn-success btn-circle btn-outline modal-historico" data-id-entidade="<?php echo $row['id_entidade'] ?>" data-toggle="modal" data-target="#modalNovoHistorico"><i class="fa fa-pencil"></i></a>
                            </td>
                        </tr><tr>
                            <td>Sistema Brasileiro de Televisão - SBT</td>
                            <td>Silvio Santos</td>
                            <td>0800 12121212</td>
                            <td>são Paulo</td>
                            <td>20/10/2016</td>
                            <td>20/12/2016</td>
                            <td><a href="#"><i class="fa fa-check text-navy"></i></a>
<a class="btn btn-success btn-circle btn-outline modal-historico" data-id-entidade="<?php echo $row['id_entidade'] ?>" data-toggle="modal" data-target="#modalNovoHistorico"><i class="fa fa-pencil"></i></a>
                            </td>
                        </tr>
                        <tr>
                            <td>Pizzaria do Faustão</td>
                            <td>Fausto Silva</td>
                            <td>0800 10101010</td>
                            <td>Rio de Janeiro</td>
                            <td>13/05/2016</td>
                            <td>02/06/2020</td>
                            <td><a href="#"><i class="fa fa-check text-navy"></i></a>
<a class="btn btn-success btn-circle btn-outline modal-historico" data-id-entidade="<?php echo $row['id_entidade'] ?>" data-toggle="modal" data-target="#modalNovoHistorico"><i class="fa fa-pencil"></i></a>
                            </td>
                        </tr>
                        <div class="modal inmodal" id="modalNovoHistorico" tabindex="-1" role="dialog" aria-hidden="true">
                                                            <div class="modal-dialog">
                                                            <div class="modal-content animated bounceInRight">
                                                                    <div class="modal-header">
                                                                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                                                                        <i class="fa fa-rebel modal-icon"></i>
                                                                        <h4 class="modal-title">Novo Contato</h4>
                                                                        <small class="font-bold">Preencha o que foi falado com a cliente.</small>
                                                                    </div>
                                                                    <div id="modalbody">

                                                                    </div>

                                                                </div>
                                                            </div>
                        </div>

                        </tbody>
                        <tfoot>
                        <tr>
                            <td colspan="5">
                                <ul class="pagination pull-right"></ul>
                            </td>
                        </tr>
                        </tfoot>
                    </table>

                    </div>
                </div>
            </div>
        </div>

        <script>
        $(function () {
            $('.modal-historico').click(function () {

                var id = $(this).data('id-entidade');

                $('#modalbody').load('<?php echo $this->baseUrl('historico/novo/id_entidade/') ?>' + id);
            });

        });

            $(document).ready(function() {

                $('.footable').footable();
                $('.footable2').footable();

            });

        </script>
