<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Login -  Gercom</title>
    <link href="./../img/favicon.ico" rel="icon" type="image/x-icon"/>
    <link href="./../img/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    <link href="<?php echo $this->baseUrl('temas/Inspinia/css/bootstrap.min.css'); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl('temas/Inspinia/font-awesome/css/font-awesome.css'); ?>" rel="stylesheet">

    <link href="<?php echo $this->baseUrl('temas/Inspinia/css/animate.css'); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl('temas/Inspinia/css/style.css'); ?>" rel="stylesheet">

<!--<style rel="stylesheet">-->
<!--    #meio {-->
<!--            margin-top: .2cm;-->
<!--        }-->
<!--</style>-->

</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen animated fadeInDown" id="meio">
        <div>
            <div>

                <h1 class="logo-name">
                    <img src="./../img/loading.gif"  width="140" height="140">
                </h1>

            </div>
            <h3><strong>Bem-Vindo !</strong></h3>
            <p>Sistema de Gerenciamento de Comunicações.</p>

            <form class="m-t" role="form" action="<?php echo $this->baseUrl('login/autentica'); ?>">
                <div class="form-group">
                    <input type="email" class="form-control" placeholder="Usuario" name="email" required="">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Senha" name="senha" required="">
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">Login</button>
            </form>
        </div>
    </div>
    <div class="footer">
        <div align="center">
            <p class="m-t"> <strong>GERCOM - Fábrica de Softwares Jr.</strong> </p>

        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/jquery-2.1.1.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/bootstrap.min.js'); ?>"></script>

</body>

</html>