<!---->
<!--/**-->
<!-- * Created by PhpStorm.-->
<!-- * User: diego-->
<!-- * Date: 02/09/2016-->
<!-- * Time: 18:49-->
<!-- */-->

<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Login Gercom</title>

    <link href="<?php echo $this->baseUrl('temas/Inspinia/css/bootstrap.min.css'); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl('temas/Inspinia/font-awesome/css/font-awesome.css'); ?>" rel="stylesheet">

    <link href="<?php echo $this->baseUrl('temas/Inspinia/css/animate.css'); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl('temas/Inspinia/css/style.css'); ?>" rel="stylesheet">

</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name">
                    <img src="./../img/Logo_Folha.png"  width="120" height="120">
                </h1>

            </div>
            <h3>Bem-Vindo !</h3>
            <p>Sistema de Gerenciamento de Comunicações.</p>
            <p>Faça o Login</p>
            <form class="m-t" role="form" action="#">
                <div class="form-group">
                    <input type="email" class="form-control" placeholder="Usuario" required="">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Senha" required="">
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">Login</button>

                <a href="#"><small>Não Tem Cadastro ? </small></a>
                <p class="text-muted text-center"><small>Fale com um Administrador e peça sua conta.</small></p>
                <a class="btn btn-sm btn-white btn-block" href="#">Adm</a>
            </form>
            <p class="m-t"> <small>GERCOM - Fábrica de Softwares Jr.</small> </p>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/jquery-2.1.1.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/bootstrap.min.js'); ?>"></script>

</body>

</html>