<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">

    <title>GERCOM</title>

    <link href="<?php echo $this->baseUrl('img/favicon.ico'); ?>" rel="icon" type="image/x-icon"/>
    <link href="img/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    <link href="<?php echo $this->baseUrl('temas/Inspinia/css/bootstrap.min.css'); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl('temas/Inspinia/font-awesome/css/font-awesome.css'); ?>" rel="stylesheet">

    <!-- Sweet Alert -->
    <link href="<?php echo $this->baseUrl('temas/Inspinia/css/plugins/sweetalert/sweetalert.css'); ?>" rel="stylesheet">
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/sweetalert/sweetalert.min.js'); ?>"></script>

    <!-- Toastr style -->
    <link href="<?php echo $this->baseUrl('temas/Inspinia/css/plugins/toastr/toastr.min.css'); ?>" rel="stylesheet">

    <!-- Gritter -->
    <link href="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/gritter/jquery.gritter.css'); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl('temas/Inspinia/css/animate.css'); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl('temas/Inspinia/css/style.css'); ?>" rel="stylesheet">

    <!-- Mainly scripts -->
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/jquery-2.1.1.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/bootstrap.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/metisMenu/jquery.metisMenu.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/slimscroll/jquery.slimscroll.min.js'); ?>"></script>

    <!-- Flot -->
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/flot/jquery.flot.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/flot/jquery.flot.tooltip.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/flot/jquery.flot.spline.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/flot/jquery.flot.resize.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/flot/jquery.flot.pie.js'); ?>"></script>

    <!-- Peity -->
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/peity/jquery.peity.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/demo/peity-demo.js'); ?>"></script>

    <!-- Custom and plugin javascript -->
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/inspinia.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/pace/pace.min.js'); ?>"></script>

    <!-- jQuery UI -->
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/jquery-ui/jquery-ui.min.js'); ?>"></script>

    <!-- GITTER -->
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/gritter/jquery.gritter.min.js'); ?>"></script>

    <!-- Sparkline -->
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/sparkline/jquery.sparkline.min.js'); ?>"></script>

    <!-- Sparkline demo data  -->
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/demo/sparkline-demo.js'); ?>"></script>

    <!-- ChartJS-->
    <script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/chartJs/Chart.min.js'); ?>"></script>



</head>

<body class="pace-done mini-navbar">
<div id="wrapper">
    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header">
                    <div class="dropdown profile-element">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="block m-t-xs"> <strong class="font-bold">Diego Denizard</strong>
                            </span>

                            <span class="text-muted text-xs block">Desenvolvedor Front-End<b class=""></b>
                            </span>
                        </a>
                    </div>

                    <div class="logo-element">
                        <a  href="<?php echo $this->baseUrl('index/home'); ?>">
                        <img src="./../img/Logo_Folha.png" width="60" height="60">
                        </a>
                    </div>
                </li>

                <li>
                    <a href="<?php echo $this->baseUrl('index/home') ?>"><i class="fa fa-th-large"></i> <span class="nav-label">Menu Principal</span> <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="<?php echo $this->baseUrl('index/home') ?>">Home</a></li>
                        <li><a href="<?php echo $this->baseUrl('perfil/perfil') ?>">Perfil</a></li>
                        <li><a href="<?php echo $this->baseUrl('funcionario/funcionario') ?>">Funcionário</a></li>
                    </ul>
                </li>

                <li>
                    <a href="#"><i class="fa fa-bar-chart-o"></i> <span class="nav-label">Atendimento</span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse">
                        <li>
                            <a href="#">Clientes<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li>
                                    <a href="<?php echo $this->baseUrl('cliente/pagina') ?>">&nbsp Meus Clientes</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->baseUrl('cliente/formulario') ?>">&nbsp Novo Cliente</a>
                                </li>
                            </ul>
                        </li>
                        <li><a href="<?php echo $this->baseUrl('historico/historico') ?>">Historico</a></li>
                        <li><a href="<?php echo $this->baseUrl('agenda/calendario')?>">Agenda</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="fa fa-edit"></i> <span class="nav-label">Calendario</span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse">
                        <li><a href="#">Compromissos Futuros</a></li>
                        <li><a href="#">Ultimos historicos</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="fa fa-table"></i> <span class="nav-label">Relatorios</span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse">
                        <li><a href="#">Individuais</a></li>
                        <li><a href="#">Gerais</a></li>
                        <li><a href="#">Resumo</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>

    <div id="page-wrapper" class="bg-success dashbard-1">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    <li>
                        <span class="m-r-sm text-muted welcome-message">GERCOM - Jundiaí Embalagens</span>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                            <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
                        </a>
                        <ul class="dropdown-menu dropdown-alerts">
                            <li>
                                <div>
                                    <i class="fa fa-envelope fa-fw"></i> Vc tem tal compromisso hj
                                </div>
                            </li>

                            <li class="divider"></li>

                            <li>
                                <div>
                                    <i class="fa fa-twitter fa-fw"></i> Ligar para Silvio
                                </div>
                            </li>

                            <li class="divider"></li>

                            <li>
                                <div class="text-center link-block">
                                    <a href="#agenda">
                                        <strong>Ver todos os compromissos</strong>
                                        <i class="fa fa-angle-right"></i>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </li>

                    <li>
                        <a href="<?php echo $this->baseUrl('login/logout'); ?>">
                            <i class="fa fa-sign-out"></i> Sair
                        </a>
                    </li>
                </ul>
            </nav>
</div>
                <?php echo $this->layout()->content; ?>

            <div class="footer">
                <div class="pull-right">
                    IESB
            </div>
                <div>
                    <strong>Copyright</strong> Fábrica de Softwares Jr. & Jundiaí Embalagens &copy; 2016
                </div>
            </div>
        </div>
        </div>
</div>

</body>
</html>
