<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">

    <title>GERCOM</title>

    <link href="<?php echo $this->baseUrl('temas/Inspinia/css/bootstrap.min.css'); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl('temas/Inspinia/font-awesome/css/font-awesome.css'); ?>" rel="stylesheet">

    <!-- Toastr style -->
    <link href="<?php echo $this->baseUrl('temas/Inspinia/css/plugins/toastr/toastr.min.css'); ?>" rel="stylesheet">

    <!-- Gritter -->
    <link href="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/gritter/jquery.gritter.css'); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl('temas/Inspinia/css/animate.css'); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl('temas/Inspinia/css/style.css'); ?>" rel="stylesheet">

</head>

<body class="pace-done mini-navbar">
<div id="wrapper">
    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header">
                    <div class="dropdown profile-element">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">Diego Denizard</strong>
                             </span> <span class="text-muted text-xs block">Desenvolvedor Front-End<b class=""></b></span> </span> </a>

                    </div>
                    <div class="logo-element">
                        <img src="./../img/Logo_Folha.png" width="60" height="60" href="<?php echo $this->baseUrl('index/home'); ?>">
                    </div>
                </li>
                <li class="active">
                    <a href="<?php echo $this->baseUrl('index/home') ?>"><i class="fa fa-th-large"></i> <span class="nav-label">Cadastros</span> <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li class="active"><a href="<?php echo $this->baseUrl('index/home') ?>">Home</a></li>
                        <li><a href="#">Cliente</a></li>
                        <li><a href="<?php echo $this->baseUrl('perfil/perfil') ?>">Perfil</a></li>
                        <li><a href="<?php echo $this->baseUrl('atendente/atendente') ?>">Atendente</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="fa fa-bar-chart-o"></i> <span class="nav-label">Atendimento</span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse">
                        <li><a href="#">Contato</a></li>
                        <li><a href="#">Clientes</a></li>
                        <li><a href="#">Agenda</a></li>
                        <li><a href="#">Outro</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="fa fa-edit"></i> <span class="nav-label">Calendario</span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse">
                        <li><a href="#">Compromissos Futuros</a></li>
                        <li><a href="#">Ultimos contatos</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="fa fa-table"></i> <span class="nav-label">Relatorios</span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse">
                        <li><a href="#">Individuais</a></li>
                        <li><a href="#">Gerais</a></li>
                        <li><a href="#">Resumo</a></li>
                    </ul>
                </li>
        </div>
    </nav>

    <div id="page-wrapper" class="bg-success dashbard-1">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>

                </div>
                <ul class="nav navbar-top-links navbar-right">
                    <li>
                        <span class="m-r-sm text-muted welcome-message">GERCOM - Jundiaí Embalagens</span>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                            <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
                        </a>
                        <ul class="dropdown-menu dropdown-alerts">
                            <li>

                                    <div>
                                        <i class="fa fa-envelope fa-fw"></i> Vc tem tal compromisso hj
                                    </div>
                            </li>
                            <li class="divider"></li>
                            <li>
                                    <div>
                                        <i class="fa fa-twitter fa-fw"></i> Ligar para Silvio
                                    </div>

                            </li>
                            <li class="divider"></li>
                            <li>
                                <div class="text-center link-block">
                                    <a href="#agenda">
                                        <strong>Ver todos os compromissos</strong>
                                        <i class="fa fa-angle-right"></i>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </li>


                    <li>
                        <a href="<?php echo $this->baseUrl('login/login'); ?>">
                            <i class="fa fa-sign-out"></i> Sair
                        </a>
                    </li>
                </ul>
            </nav>
        </div>

                <div class="footer">
                    <div class="pull-right">
                        IESB
                    </div>
                    <div>
                        <strong>Copyright</strong> Fábrica de Softwares Jr. & Jundiaí Embalagens &copy; 2016
                    </div>
                </div>
        <div class="container"  style="margin-top: 35px;">
            <?php echo $this->layout()->content; ?>
        </div>
<!-- Mainly scripts -->
<script src="<?php echo $this->baseUrl('temas/Inspinia/js/jquery-2.1.1.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('temas/Inspinia/js/bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/metisMenu/jquery.metisMenu.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/slimscroll/jquery.slimscroll.min.js'); ?>"></script>

<!-- Flot -->
<script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/flot/jquery.flot.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/flot/jquery.flot.tooltip.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/flot/jquery.flot.spline.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/flot/jquery.flot.resize.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/flot/jquery.flot.pie.js'); ?>"></script>

<!-- Peity -->
<script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/peity/jquery.peity.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('temas/Inspinia/js/demo/peity-demo.js'); ?>"></script>

<!-- Custom and plugin javascript -->
<script src="<?php echo $this->baseUrl('temas/Inspinia/js/inspinia.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/pacepace/pace.min.js'); ?>"></script>

<!-- jQuery UI -->
<script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/jquery-ui/jquery-ui.min.js'); ?>"></script>

<!-- GITTER -->
<script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/gritter/jquery.gritter.min.js'); ?>"></script>

<!-- Sparkline -->
<script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/sparkline/jquery.sparkline.min.js'); ?>"></script>

<!-- Sparkline demo data  -->
<script src="<?php echo $this->baseUrl('temas/Inspinia/js/demo/sparkline-demo.js'); ?>"></script>

<!-- ChartJS-->
<script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/chartJs/Chart.min.js'); ?>"></script>

<!-- Toastr -->
<script src="<?php echo $this->baseUrl('temas/Inspinia/js/plugins/toastr/toastr.min.js'); ?>"></script>


<script>
    $(document).ready(function() {
        setTimeout(function() {
            toastr.options = {
                closeButton: true,
                progressBar: true,
                showMethod: 'slideDown',
                positionClass: 'toast-top-center',
                timeOut: 1200
            };
            toastr.success('Bem-Vindo ao Gercom !', 'GERCOM');

        }, 500);


        var data1 = [
            [0,4],[1,8],[2,5],[3,10],[4,4],[5,16],[6,5],[7,11],[8,6],[9,11],[10,30],[11,10],[12,13],[13,4],[14,3],[15,3],[16,6]
        ];
        var data2 = [
            [0,1],[1,0],[2,2],[3,0],[4,1],[5,3],[6,1],[7,5],[8,2],[9,3],[10,2],[11,1],[12,0],[13,2],[14,8],[15,0],[16,0]
        ];
        $("#flot-dashboard-chart").length && $.plot($("#flot-dashboard-chart"), [
                data1, data2
            ],
            {
                series: {
                    lines: {
                        show: false,
                        fill: true
                    },
                    splines: {
                        show: true,
                        tension: 0.4,
                        lineWidth: 1,
                        fill: 0.4
                    },
                    points: {
                        radius: 0,
                        show: true
                    },
                    shadowSize: 2
                },
                grid: {
                    hoverable: true,
                    clickable: true,
                    tickColor: "#d5d5d5",
                    borderWidth: 1,
                    color: '#d5d5d5'
                },
                colors: ["#1ab394", "#1C84C6"],
                xaxis:{
                },
                yaxis: {
                    ticks: 4
                },
                tooltip: false
            }
        );

        var doughnutData = [
            {
                value: 300,
                color: "#a3e1d4",
                highlight: "#1ab394",
                label: "App"
            },
            {
                value: 50,
                color: "#dedede",
                highlight: "#1ab394",
                label: "Software"
            },
            {
                value: 100,
                color: "#A4CEE8",
                highlight: "#1ab394",
                label: "Laptop"
            }
        ];

        var doughnutOptions = {
            segmentShowStroke: true,
            segmentStrokeColor: "#fff",
            segmentStrokeWidth: 2,
            percentageInnerCutout: 45, // This is 0 for Pie charts
            animationSteps: 100,
            animationEasing: "easeOutBounce",
            animateRotate: true,
            animateScale: false
        };

        var ctx = document.getElementById("doughnutChart").getContext("2d");
        var DoughnutChart = new Chart(ctx).Doughnut(doughnutData, doughnutOptions);

        var polarData = [
            {
                value: 300,
                color: "#a3e1d4",
                highlight: "#1ab394",
                label: "App"
            },
            {
                value: 140,
                color: "#dedede",
                highlight: "#1ab394",
                label: "Software"
            },
            {
                value: 200,
                color: "#A4CEE8",
                highlight: "#1ab394",
                label: "Laptop"
            }
        ];

        var polarOptions = {
            scaleShowLabelBackdrop: true,
            scaleBackdropColor: "rgba(255,255,255,0.75)",
            scaleBeginAtZero: true,
            scaleBackdropPaddingY: 1,
            scaleBackdropPaddingX: 1,
            scaleShowLine: true,
            segmentShowStroke: true,
            segmentStrokeColor: "#fff",
            segmentStrokeWidth: 2,
            animationSteps: 100,
            animationEasing: "easeOutBounce",
            animateRotate: true,
            animateScale: false
        };
        var ctx = document.getElementById("polarChart").getContext("2d");
        var Polarchart = new Chart(ctx).PolarArea(polarData, polarOptions);

    });
</script>


</body>
</html>

